site_name: Oh my Grid!
site_url: 'https://ohmygrid.org/'
site_description: We aim to contribute to mapping countries' electricity grid systems around the world. We strive to improving the power infrastructure data on OpenStreetMap, to enhance global energy system modeling. 
repo_name: 'Oh my Grid!'
repo_url: 'https://github.com/open-energy-transition/Oh-my-Grid'

nav:
  - The Initiative 🚀: index.md
  - Starter-kit tutorial 🛠️: starter-kit.md
  - Start mapping 📍: start_mapping.md
  - Tools 🧰: tools.md
  - Advanced kit ⚡: advanced-kit.md
  - Awesome List 🌟: awesome.md
  - Contribute & KPI 🤝: contributing.md
  - Validation checks ✅:  validation-checks.md
  - Blog 💭:
      2025:
        - "Liberate the Grid": blog/firstrename.md

copyright:    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
      Creative Commons Attribution 4.0 International License   </a>

theme:
  name: material
  favicon: images/preview.jpg
  logo: images/logo.jpg
  palette:
    # Light Mode
    - scheme: default
      primary: green
      accent: indigo
      toggle: false 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top

extra_css:
    - stylesheets/extra.css
    - stylesheets/landing.css
    - stylesheets/blog.css

extra_javascript:
  - javascripts/progress.js


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.md_in_html
  - markdown.extensions.attr_list

  
  
